# Site settings
title: Thymeso
#email: contact@thymeso.com
email: contact@thymeso.com # temporary, until above email is ready
description: > # this means to ignore newlines until "baseurl:"
  Thymeso stands for the delight our small but dynamic team is doing things with.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.thymeso.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


exclude: ["doc", "docker-compose.yml", "README.md"]